### ISSUE TITLE
执行scrapy crawl woaidu出错

### ISSUE THREAD

**Issue by josephok** [gnemoug/distribute_crawler#13]
<pre>
$ scrapy crawl woaidu
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 4, in <module>
    execute()
  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 143, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 89, in _run_print_help
    func(*a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 150, in _run_command
    cmd.run(args, opts)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/commands/crawl.py", line 47, in run
    crawler = self.crawler_process.create_crawler()
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 87, in create_crawler
    self.crawlers[name] = Crawler(self.settings)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 20, in __init__
    self.stats = load_object(settings['STATS_CLASS'])(self)
  File "/home/joe/test/scrapy/woaidu_crawler/woaidu_crawler/statscol/graphite.py", line 209, in __init__
    self._graphiteclient = GraphiteClient(host,port)
  File "/home/joe/test/scrapy/woaidu_crawler/woaidu_crawler/statscol/graphite.py", line 27, in __init__
    self._sock.connect((host,port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused

</pre>

**Comment by gnemoug** [comment]
graphite没有部署好

**Comment by heber** [comment]
请问下graphite应该怎么部署?谢谢！

**Comment by TylerzhangZC** [comment]
按照下面这个链接里面去安装好graphite并start后就可以了
http://www.vpsee.com/2012/05/install-graphite-on-ubuntu-12-04/

**Comment by CoolView** [comment]
我也这个问题，请问是如何解决的？graphite重新部署了几次

**Comment by CoolView** [comment]
注意要 每次启动carbon
$ cd /opt/graphite/
$ sudo ./bin/carbon-cache.py start

**Comment by lDaisy847800926** [comment]
我无法运行你的代码呀，是直接执行spider文件下的代码吗
