### ISSUE TITLE
有人用python3的venv成功连上pymongo吗

### ISSUE THREAD

**Issue by xiaocwan** [gnemoug/distribute_crawler#36]
起mongd时候停在2018-12-19T09:59:56.020+0800 I NETWORK  [initandlisten] waiting for connections on port 27017
不知道是否正常

**Comment by xiaocwan** [comment]
这时候起sudo python init_sharding_mongodb.py --path=/usr/bin
的时候出现
```
M3: 2018-12-19T10:00:55.054+0800 I NETWORK  [initandlisten] waiting for connections on port 30003
M3: 2018-12-19T10:00:55.055+0800 I CONTROL  [LogicalSessionCacheReap] Sessions collection is not set up; waiting until next sessions reap interval: sharding state is not yet initialized
Traceback (most recent call last):
  File "init_sharding_mongodb.py", line 296, in <module>
M3: 2018-12-19T10:00:59.165+0800 I NETWORK  [listener] connection accepted from 127.0.0.1:51310 #1 (1 connection now open)
    config.settings.save({'_id':'chunksize', 'value':CHUNK_SIZE}, safe=True)
  File "/usr/lib64/python2.7/site-packages/pymongo/collection.py", line 3133, in save
    write_concern = WriteConcern(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'safe'
C1: 2018-12-19T10:00:59.166+0800 I NETWORK  [listener] connection accepted from 127.0.0.1:43478 #2 (1 connection now open)
M3: 2018-12-19T10:00:59.165+0800 I NETWORK  [conn1] end connection 127.0.0.1:51310 (0 connections now open)
C1: 2018-12-19T10:00:59.167+0800 I NETWORK  [conn2] received client metadata from 127.0.0.1:43478 conn2: { driver: { name: "PyMongo", version: "3.7.2" }, os: { type: "Linux", name: "Fedora 29 Twenty Nine", architecture: "x86_64", version: "4.19.8-300.fc29.x86_64" }, platform: "CPython 2.7.15.final.0" }
C1: 2018-12-19T10:01:10.007+0800 I SHARDING [shard registry reload] Periodic reload of shard registry failed  :: caused by :: NotAReplicaSet: could not get updated shard list from config server :: caused by :: node needs to be a replica set member to use read concern; will retry after 30s


```
